name: SimpleEssentials
version: '${project.version}'
main: com.github.arnhav.simpleessentials.SimpleEssentials
api-version: 1.18
authors: [ Tyrriel ]
commands:
  warp:
    usage: /<command>
  setwarp:
    usage: /<command>
  remwarp:
    usage: /<command>
  back:
    usage: /<command>
  gm:
    usage: /<command>
  gm0:
    usage: /<command>
  gm1:
    usage: /<command>
  gm2:
    usage: /<command>
  gm3:
    usage: /<command>
  gms:
    usage: /<command>
  gmc:
    usage: /<command>
  gma:
    usage: /<command>
  gmsp:
    usage: /<command>
  fix:
    usage: /<command>
  heal:
    usage: /<command>
  speed:
    usage: /<command>