name: Create Release

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Get project version
        run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
        id: get-version
      - name: Build with Maven
        run: mvn package
      - name: Create or Update Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag: ${{ env.RELEASE_VERSION }}
          name: ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
          allowUpdates: true
          replacesArtifacts: true
          artifacts: target/SimpleEssentials-${{ env.RELEASE_VERSION }}.jar
          artifactContentType: application/java-archive